-- 000001_initial_schema.down.sql
-- Drop all tables in reverse dependency order

DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS file_uploads CASCADE;
DROP TABLE IF EXISTS word_filters CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS bans CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS poll_votes CASCADE;
DROP TABLE IF EXISTS poll_options CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS stickers CASCADE;
DROP TABLE IF EXISTS sticker_packs CASCADE;
DROP TABLE IF EXISTS custom_emoji CASCADE;
DROP TABLE IF EXISTS invites CASCADE;
DROP TABLE IF EXISTS e2ee_one_time_prekeys CASCADE;
DROP TABLE IF EXISTS e2ee_signed_prekeys CASCADE;
DROP TABLE IF EXISTS e2ee_identity_keys CASCADE;
DROP TABLE IF EXISTS dm_messages CASCADE;
DROP TABLE IF EXISTS dm_channel_members CASCADE;
DROP TABLE IF EXISTS dm_channels CASCADE;
DROP TABLE IF EXISTS forum_post_tags CASCADE;
DROP TABLE IF EXISTS forum_tags CASCADE;
DROP TABLE IF EXISTS thread_members CASCADE;
DROP TABLE IF EXISTS threads CASCADE;
DROP TABLE IF EXISTS pins CASCADE;
DROP TABLE IF EXISTS read_states CASCADE;
DROP TABLE IF EXISTS message_mentions CASCADE;
DROP TABLE IF EXISTS message_reactions CASCADE;
DROP TABLE IF EXISTS message_attachments CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS channel_permission_overrides CASCADE;
DROP TABLE IF EXISTS channels CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS guild_member_roles CASCADE;
DROP TABLE IF EXISTS guild_members CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS guilds CASCADE;
DROP TABLE IF EXISTS email_verifications CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;
DROP TABLE IF EXISTS totp_secrets CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS user_passwords CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Drop enum types
DROP TYPE IF EXISTS audit_action;
DROP TYPE IF EXISTS report_status;
DROP TYPE IF EXISTS upload_status;
DROP TYPE IF EXISTS invite_type;
DROP TYPE IF EXISTS dm_channel_type;
DROP TYPE IF EXISTS message_type;
DROP TYPE IF EXISTS channel_type;
DROP TYPE IF EXISTS user_status;
